spring.application.name=UT1_Entorno_Servidor
# Configuración del servidor
server.port=8080
server.servlet.context-path=/biblioteca

# Configuración de la aplicación
spring.application.name=Biblioteca Digital

# Thymeleaf (motor de plantillas)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.root=INFO
logging.level.com.biblioteca=DEBUG

# Dev Tools
spring.devtools.restart.enabled=true